[package]
name = "git"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lib]
path = "src/git.rs"

[dependencies]
anyhow.workspace = true
clock.workspace = true
git2.workspace = true
lazy_static.workspace = true
log.workspace = true
smol.workspace = true
sum_tree.workspace = true
text.workspace = true
fs.workspace = true
parking_lot.workspace = true

[dev-dependencies]
unindent.workspace = true

[features]
test-support = []
